//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class money_logs
    {
        public int id { get; set; }
        public Nullable<int> loai { get; set; }
        public string noi_dung { get; set; }
        public Nullable<int> so_tien { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    }
}
